services:
  nginx:
    image: nginx:alpine
    container_name: bant-nginx
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_auth/.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - api
      - ui
    restart: unless-stopped
    networks:
      - default
      - internal

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bant-api
    environment:
      - API_BASE=http://api:8000
      - GIGACHAT_AUTH_KEY=${GIGACHAT_AUTH_KEY}
      - GIGACHAT_MODEL=${GIGACHAT_MODEL:-GigaChat-Pro}
      - GIGACHAT_SCOPE=${GIGACHAT_SCOPE:-GIGACHAT_API_PERS}
      - GIGACHAT_VERIFY_SSL=${GIGACHAT_VERIFY_SSL:-true}
      - GIGACHAT_AUTH_URL=${GIGACHAT_AUTH_URL:-https://ngw.devices.sberbank.ru:9443/api/v2/oauth}
      - GIGACHAT_API_URL=${GIGACHAT_API_URL:-https://gigachat.devices.sberbank.ru/api/v1}
      - STORAGE_TYPE=${STORAGE_TYPE:-json}
      - STORAGE_PATH=${STORAGE_PATH:-data/sessions.json}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: bant-ui
    environment:
      - API_BASE=http://api:8000
    depends_on:
      - api
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  data:

networks:
  internal:
    driver: bridge
